// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using Update;
using System;
using UnityEngine;

namespace Update.Map
{
	public class TileMap
	{
		private Tile[,] tiles;

		public TileMap(int w, int h){
			tiles = new Tile[w, h];
		}

		public Tile this[Vector index]
		{
			get { try { return tiles [index.X, index.Y]; } catch(IndexOutOfRangeException e){ Debug.Log("EXCEPTION: "+index); return null; }}
			set { tiles [index.X, index.Y] = value; }
		}

		public Tile this [int x, int y] {
			get { return tiles [x, y]; }
			set { tiles [x, y] = value; }
		}

		public override string ToString(){
			string ret = "[";
			foreach(Tile tile in tiles){
				ret += tile ? tile.Index.ToString() : "(NULL)";
			}
			return ret + "]";
		}
	}
}

